# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello <- function() {
    .Call('_SemiMaRkov_rcpp_hello', PACKAGE = 'SemiMaRkov')
}

