# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Full (non-normalised) Upper Incomplete Gamma Function
#'
#' Return the full (non-normalised) upper incomplete gamma function; this is a wrapper for
#' \code{tgamma}, found in \url{http://www.boost.org/doc/libs/1_46_0/libs/math/doc/sf_and_dist/html/math_toolkit/special/sf_gamma/igamma.html}
#'
#' @param a numeric
#' @param z numeric
#'
#' @export
tgamma_boost <- function(a, z) {
    .Call('_SemiMaRkov_tgamma_boost', PACKAGE = 'SemiMaRkov', a, z)
}

#' Full (non-normalised) Lower Incomplete Gamma Function
#'
#' Return the full (non-normalised) lower incomplete gamma function; this is a wrapper for
#' \code{tgamma_lower}, found in \url{http://www.boost.org/doc/libs/1_46_0/libs/math/doc/sf_and_dist/html/math_toolkit/special/sf_gamma/igamma.html}
#'
#' @param a numeric
#' @param z numeric
#'
#' @export
tgamma_lower_boost <- function(a, z) {
    .Call('_SemiMaRkov_tgamma_lower_boost', PACKAGE = 'SemiMaRkov', a, z)
}

#' Normalised Lower Incomplete Gamma Function
#'
#' Return the normalised lower incomplete gamma function; this is a wrapper for
#' \code{gamma_p}, found in \url{http://www.boost.org/doc/libs/1_46_0/libs/math/doc/sf_and_dist/html/math_toolkit/special/sf_gamma/igamma.html}
#'
#' @param a numeric
#' @param z numeric
#'
#' @export
gamma_p_boost <- function(a, z) {
    .Call('_SemiMaRkov_gamma_p_boost', PACKAGE = 'SemiMaRkov', a, z)
}

#' Normalised Upper Incomplete Gamma Function
#'
#' Return the normalised upper incomplete gamma function; this is a wrapper for
#' \code{gamma_p_inv}, found in \url{http://www.boost.org/doc/libs/1_46_0/libs/math/doc/sf_and_dist/html/math_toolkit/special/sf_gamma/igamma.html}
#'
#' @param a numeric
#' @param z numeric
#'
#' @export
gamma_p_inv_boost <- function(a, z) {
    .Call('_SemiMaRkov_gamma_p_inv_boost', PACKAGE = 'SemiMaRkov', a, z)
}

#' @export
rcpp_hello <- function() {
    .Call('_SemiMaRkov_rcpp_hello', PACKAGE = 'SemiMaRkov')
}

